<a href="https://colab.research.google.com/github/davidcontrerasf/PythonDataScienceHandbook/blob/main/notebooks/02_02_The_Basics_Of_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Basics of NumPy Arrays

La manipulación de datos en Python es casi sinónimo de la manipulación de arreglos de NumPy: incluso herramientas más recientes como Pandas ([Parte 3](03.00-Introduction-to-Pandas.ipynb)) están construidas alrededor de los arreglos de NumPy.  
Este capítulo presentará varios ejemplos de cómo usar la manipulación de arreglos de NumPy para acceder a datos y subarreglos, y para dividir, cambiar la forma y unir arreglos.  
Aunque los tipos de operaciones mostrados aquí puedan parecer un poco secos y académicos, constituyen los bloques de construcción de muchos otros ejemplos utilizados a lo largo del libro.  
¡Familiarízate bien con ellos!

Aquí cubriremos algunas categorías de manipulaciones básicas de arreglos:

- **Atributos de los arreglos**: Determinar el tamaño, forma, consumo de memoria y tipos de datos de los arreglos.  
- **Indexación de arreglos**: Obtener y establecer los valores de elementos individuales de un arreglo.  
- **Corte de arreglos**: Obtener y establecer subarreglos más pequeños dentro de un arreglo más grande.  
- **Reconfiguración de arreglos**: Cambiar la forma de un arreglo dado.  
- **Unión y división de arreglos**: Combinar múltiples arreglos en uno y dividir un arreglo en varios.  

## NumPy Array Attributes

Primero, discutamos algunos atributos útiles de los arreglos.  
Comenzaremos definiendo arreglos aleatorios de una, dos y tres dimensiones.  
Usaremos el generador de números aleatorios de NumPy, que *sembramos* (seed) con un valor fijo para garantizar que se generen los mismos arreglos aleatorios cada vez que se ejecute este código:  

In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)  # seed for reproducibility

In [2]:
rng

Generator(PCG64) at 0x7B73EF18F3E0

In [4]:
x1 = rng.integers(10, size=6)  # one-dimensional array
x2 = rng.integers(10, size=(3, 4))  # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5))  # three-dimensional array

Cada arreglo tiene atributos, incluidos `ndim` (el número de dimensiones), `shape` (el tamaño de cada dimensión), `size` (el tamaño total del arreglo) y `dtype` (el tipo de cada elemento):  

In [5]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


For more discussion of data types, see [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb).

## Array Indexing: Accessing Single Elements

Si estás familiarizado con la indexación estándar de listas en Python, la indexación en NumPy te resultará bastante familiar.  
En un arreglo unidimensional, el valor $i^{th}$ (contando desde cero) se puede acceder especificando el índice deseado entre corchetes, al igual que con las listas de Python:  

In [6]:
x1

array([9, 3, 6, 6, 5, 0])

In [7]:
x1[0]

9

In [8]:
x1[4]

5

To index from the end of the array, you can use negative indices:

In [9]:
x1[-1]

0

In [10]:
x1[-2]

5

In a multidimensional array, items can be accessed using a comma-separated `(row, column)` tuple:

In [11]:
x2

array([[2, 5, 6, 4],
       [8, 2, 5, 6],
       [2, 7, 3, 8]])

In [12]:
x2[0, 0]

2

In [13]:
x2[2, 0]

2

In [14]:
x2[2, -1]

8

Values can also be modified using any of the preceding index notation:

In [15]:
x2[0, 0] = 12
x2

array([[12,  5,  6,  4],
       [ 8,  2,  5,  6],
       [ 2,  7,  3,  8]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value into an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [16]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 3, 6, 6, 5, 0])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (`:`) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array `x`, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values `start=0`, `stop=<size of dimension>`, `step=1`.
Let's look at some examples of accessing subarrays in one dimension and in multiple dimensions.

### One-Dimensional Subarrays

Here are some examples of accessing elements in one-dimensional subarrays:

In [17]:
x1

array([3, 3, 6, 6, 5, 0])

In [18]:
x1[:3]  # first three elements

array([3, 3, 6])

In [19]:
x1[3:]  # elements after index 3

array([6, 5, 0])

In [ ]:
x1[1:4]  # middle subarray

array([4, 0, 3])

In [20]:
x1[::2]  # every second element

array([3, 6, 5])

In [21]:
x1[1::2]  # every second element, starting at index 1

array([3, 6, 0])

A potentially confusing case is when the `step` value is negative.
In this case, the defaults for `start` and `stop` are swapped.
This becomes a convenient way to reverse an array:

In [23]:
x1[::-1]  # all elements, reversed

array([0, 5, 6, 6, 3, 3])

In [24]:
x1[4::-2]  # every second element from index 4, reversed

array([5, 6, 3])

### Multidimensional Subarrays

Multidimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [25]:
x2

array([[12,  5,  6,  4],
       [ 8,  2,  5,  6],
       [ 2,  7,  3,  8]])

In [26]:
x2[:2, :3]  # first two rows & three columns

array([[12,  5,  6],
       [ 8,  2,  5]])

In [27]:
x2[:3, ::2]  # three rows, every second column

array([[12,  6],
       [ 8,  5],
       [ 2,  3]])

In [28]:
x2[::-1, ::-1]  # all rows & columns, reversed

array([[ 8,  3,  7,  2],
       [ 6,  5,  2,  8],
       [ 4,  6,  5, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (`:`):

In [29]:
x2[:, 0]  # first column of x2

array([12,  8,  2])

In [30]:
x2[0, :]  # first row of x2

array([12,  5,  6,  4])

In the case of row access, the empty slice can be omitted for a more compact syntax:

In [31]:
x2[0]  # equivalent to x2[0, :]

array([12,  5,  6,  4])

### Subarrays as No-Copy Views

Unlike Python list slices, NumPy array slices are returned as *views* rather than *copies* of the array data.
Consider our two-dimensional array from before:

In [32]:
print(x2)

[[12  5  6  4]
 [ 8  2  5  6]
 [ 2  7  3  8]]


Let's extract a $2 \times 2$ subarray from this:

In [33]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 8  2]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [34]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 8  2]]


In [35]:
print(x2)

[[99  5  6  4]
 [ 8  2  5  6]
 [ 2  7  3  8]]


Some users may find this surprising, but it can be advantageous: for example, when working with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating Copies of Arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the `copy` method:

In [36]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 8  2]]


If we now modify this subarray, the original array is not touched:

In [37]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 8  2]]


In [38]:
print(x2)

[[99  5  6  4]
 [ 8  2  5  6]
 [ 2  7  3  8]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays, which can be done with the `reshape` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [39]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array, and in most cases the `reshape` method will return a no-copy view of the initial array.

A common reshaping operation is converting a one-dimensional array into a two-dimensional row or column matrix:

In [40]:
x = np.array([1, 2, 3])
x.reshape((1, 3))  # row vector via reshape

array([[1, 2, 3]])

In [41]:
x.reshape((3, 1))  # column vector via reshape

array([[1],
       [2],
       [3]])

A convenient shorthand for this is to use `np.newaxis` in the slicing syntax:

In [42]:
x[np.newaxis, :]  # row vector via newaxis

array([[1, 2, 3]])

In [43]:
x[:, np.newaxis]  # column vector via newaxis

array([[1],
       [2],
       [3]])

This is a pattern that we will utilize often throughout the remainder of the book.

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. NumPy also provides tools to combine multiple arrays into one, and to conversely split a single array into multiple arrays.

### Concatenation of Arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines `np.concatenate`, `np.vstack`, and `np.hstack`.
`np.concatenate` takes a tuple or list of arrays as its first argument, as you can see here:

In [44]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [45]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


And it can be used for two-dimensional arrays:

In [46]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [47]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [48]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the `np.vstack` (vertical stack) and `np.hstack` (horizontal stack) functions:

In [ ]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

Similarly, for higher-dimensional arrays, `np.dstack` will stack arrays along the third axis.

### Splitting of Arrays

The opposite of concatenation is splitting, which is implemented by the functions `np.split`, `np.hsplit`, and `np.vsplit`.  For each of these, we can pass a list of indices giving the split points:

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that *N* split points leads to *N* + 1 subarrays.
The related functions `np.hsplit` and `np.vsplit` are similar:

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, for higher-dimensional arrays, `np.dsplit` will split arrays along the third axis.